export default [
  {
    emoji: '🎉',
    entity: '&#127881;',
    code: ':tada:',
    description: 'root: begin a project | 初始化',
    name: 'tada',
    semver: null,
  },
  {
    emoji: '🚧',
    entity: '&#x1f6a7;',
    code: ':construction:',
    description: 'wip: work in progress | 进行中',
    name: 'construction',
    semver: null,
  },
  {
    emoji: '💥',
    entity: '&#x1f4a5;',
    code: ':boom:',
    description: 'feat: breaking changes | 突破性变化',
    name: 'boom',
    semver: 'major',
  },
  {
    emoji: '✨',
    entity: '&#x2728;',
    code: ':sparkles:',
    description: 'feat: introduce new features | 添加新功能',
    name: 'sparkles',
    semver: 'minor',
  },
  {
    emoji: '🥚',
    entity: '&#129370;',
    code: ':egg:',
    description: 'feat: add or update an easter egg | 添加一个复活节彩蛋',
    name: 'egg',
    semver: 'patch',
  },
  {
    emoji: '⚗️',
    entity: '&#128248;',
    code: ':alembic:',
    description: 'feat: perform experiments | 添加实验性功能',
    name: 'alembic',
    semver: 'patch',
  },
  {
    emoji: '🐛',
    entity: '&#x1f41b;',
    code: ':bug:',
    description: 'fix: fix a bug | 修复 bug',
    name: 'bug',
    semver: 'patch',
  },
  {
    emoji: '✏️',
    entity: '&#59161;',
    code: ':pencil2:',
    description: 'fix: fix typos | 修复 typo',
    name: 'pencil2',
    semver: 'patch',
  },
  {
    emoji: '🔒️',
    entity: '&#x1f512;',
    code: ':lock:',
    description: 'fix: fix security issues | 修复安全问题',
    name: 'lock',
    semver: 'patch',
  },
  {
    emoji: '⚡️',
    entity: '&#x26a1;',
    code: ':zap:',
    description: 'perf: improve performance | 提升性能',
    name: 'zap',
    semver: 'patch',
  },
  {
    emoji: '♻️',
    entity: '&#x2672;',
    code: ':recycle:',
    description: 'refactor: refactor code | 重构代码',
    name: 'recycle',
    semver: null,
  },
  {
    emoji: '🏗️',
    entity: '&#1f3d7;',
    code: ':building_construction:',
    description: 'refactor: make architectural changes | 进行架构更改',
    name: 'building-construction',
    semver: null,
  },
  {
    emoji: '📝',
    entity: '&#x1f4dd;',
    code: ':memo:',
    description: 'docs: add or update documentation | 撰写文档',
    name: 'memo',
    semver: null,
  },
  {
    emoji: '📄',
    entity: '&#1f4c4;',
    code: ':page_facing_up:',
    description: 'docs: add or update license | 添加或更新许可证',
    name: 'page-facing-up',
    semver: null,
  },
  {
    emoji: '👥',
    entity: '&#128101;',
    code: ':busts_in_silhouette:',
    description: 'docs: add or update contributor(s) | 添加贡献者',
    name: 'chore: busts-in-silhouette',
    semver: null,
  },
  {
    emoji: '✅',
    entity: '&#x2705;',
    code: ':white_check_mark:',
    description: 'test: add or update tests | 增加测试',
    name: 'white-check-mark',
    semver: null,
  },
  {
    emoji: '⏪️',
    entity: '&#9194;',
    code: ':rewind:',
    description: 'revert: revert changes | 回滚',
    name: 'rewind',
    semver: 'patch',
  },
  {
    emoji: '🔀',
    entity: '&#128256;',
    code: ':twisted_rightwards_arrows:',
    description: 'merge: merge branches | 合并分支',
    name: 'twisted-rightwards-arrows',
    semver: null,
  },
  {
    emoji: '💄',
    entity: '&#ff99cc;',
    code: ':lipstick:',
    description:
      'style: add or update the ui and style files | 更新 UI 和样式文件',
    name: 'lipstick',
    semver: 'patch',
  },
  {
    emoji: '🍱',
    entity: '&#1f371',
    code: ':bento:',
    description: 'style: add or update assets | 添加或更新素材',
    name: 'bento',
    semver: 'patch',
  },
  {
    emoji: '💬',
    entity: '&#128172;',
    code: ':speech_balloon:',
    description: 'style: add or update text and literals | 添加或更新文字',
    name: 'speech-balloon',
    semver: 'patch',
  },
  {
    emoji: '📱',
    entity: '&#128241;',
    code: ':iphone:',
    description: 'style: work on responsive design | 致力于响应式设计',
    name: 'iphone',
    semver: 'patch',
  },
  {
    emoji: '💫',
    entity: '&#x1f4ab;',
    code: ':dizzy:',
    description:
      'style: add or update animations and transitions | 添加或更新动效',
    name: 'animation',
    semver: 'patch',
  },
  {
    emoji: '🎨',
    entity: '&#x1f3a8;',
    code: ':art:',
    description:
      'style: improve structure / format of the code | 改进代码结构 / 代码格式',
    name: 'art',
    semver: null,
  },
  {
    emoji: '💡',
    entity: '&#128161;',
    code: ':bulb:',
    description: 'style: add or update comments in source code | 添加代码注释',
    name: 'bulb',
    semver: null,
  },
  {
    emoji: '🏷️',
    entity: '&#127991;',
    code: ':label:',
    description: 'style: add or update types | 添加更新类型',
    name: 'label',
    semver: 'patch',
  },
  {
    emoji: '📦️',
    entity: '&#1f4e6;',
    code: ':package:',
    description:
      'build: add or update compiled files or packages | 更新编译的文件或包',
    name: 'package',
    semver: 'patch',
  },
  {
    emoji: '📸',
    entity: '&#128248;',
    code: ':camera_flash:',
    description: 'build: add or update snapshots | 添加或更新快照',
    name: 'camera-flash',
    semver: null,
  },
  {
    emoji: '🚑️',
    entity: '&#128657;',
    code: ':ambulance:',
    description: 'build(hotfix): critical hotfix | 热更新补丁',
    name: 'ambulance',
    semver: 'patch',
  },
  {
    emoji: '💚',
    entity: '&#x1f49a;',
    code: ':green_heart:',
    description: 'ci: fix ci build | 修复 CI 构建问题',
    name: 'green-heart',
    semver: null,
  },
  {
    emoji: '🚨',
    entity: '&#x1f6a8;',
    code: ':rotating_light:',
    description: 'ci: fix compiler / linter warnings | 移除 linter 警告',
    name: 'rotating-light',
    semver: null,
  },
  {
    emoji: '👷',
    entity: '&#x1f477;',
    code: ':construction_worker:',
    description: 'ci: add or update ci build system | 添加 CI 构建系统',
    name: 'construction-worker',
    semver: null,
  },
  {
    emoji: '🚀',
    entity: '&#x1f680;',
    code: ':rocket:',
    description: 'chore: update / deploy stuff | 更新或部署功能',
    name: 'rocket',
    semver: null,
  },
  {
    emoji: '🔖',
    entity: '&#x1f516;',
    code: ':bookmark:',
    description: 'chore(release): release / version tags | 发行 / 版本标签',
    name: 'bookmark',
    semver: null,
  },
  {
    emoji: '⬇️',
    entity: '⬇️',
    code: ':arrow_down:',
    description: 'chore(deps): downgrade dependencies | 降级依赖',
    name: 'arrow-down',
    semver: 'patch',
  },
  {
    emoji: '⬆️',
    entity: '⬆️',
    code: ':arrow_up:',
    description: 'chore(deps): upgrade dependencies | 升级依赖',
    name: 'arrow-up',
    semver: 'patch',
  },
  {
    emoji: '📌',
    entity: '&#x1f4cc;',
    code: ':pushpin:',
    description:
      'chore(deps): pin dependencies to specific versions | 将依赖关系固定到特定版本',
    name: 'pushpin',
    semver: 'patch',
  },
  {
    emoji: '➕',
    entity: '&#10133;',
    code: ':heavy_plus_sign:',
    description: 'chore(deps): add a dependency | 增加一个依赖',
    name: 'heavy-plus-sign',
    semver: 'patch',
  },
  {
    emoji: '➖',
    entity: '&#10134;',
    code: ':heavy_minus_sign:',
    description: 'chore(deps): remove a dependency | 减少一个依赖',
    name: 'heavy-minus-sign',
    semver: 'patch',
  },
  {
    emoji: '🔨',
    entity: '&#128296;',
    code: ':hammer:',
    description:
      'chore(deps): add or update development scripts | 添加或升级命令',
    name: 'hammer',
    semver: null,
  },
  {
    emoji: '🌐',
    entity: '&#127760;',
    code: ':globe_with_meridians:',
    description:
      'chore(i18n): internationalization and localization | 国际化与本地化',
    name: 'globe-with-meridians',
    semver: 'patch',
  },
  {
    emoji: '📈',
    entity: '&#x1f4c8;',
    code: ':chart_with_upwards_trend:',
    description:
      'chore(spm): add or update analytics or track code | 添加分析或跟踪代码 / 埋点',
    name: 'chart-with-upwards-trend',
    semver: 'patch',
  },
  {
    emoji: '♿️',
    entity: '&#9855;',
    code: ':wheelchair:',
    description: 'chore(ces): improve accessibility | 无障碍 / 可用性',
    name: 'wheelchair',
    semver: 'patch',
  },
  {
    emoji: '🚸',
    entity: '&#128696;',
    code: ':children_crossing:',
    description:
      'chore(ux): improve user experience / usability | 改善用户体验',
    name: 'children-crossing',
    semver: 'patch',
  },
  {
    emoji: '🔍️',
    entity: '&#128269;',
    code: ':mag:',
    description: 'chore(seo): improve seo | 改善 seo',
    name: 'mag',
    semver: 'patch',
  },
  {
    emoji: '🔧',
    entity: '&#x1f527;',
    code: ':wrench:',
    description: 'chore: add or update configuration files | 修改配置文件',
    name: 'wrench',
    semver: 'patch',
  },
  {
    emoji: '👽️',
    entity: '&#1f47d;',
    code: ':alien:',
    description:
      'chore: update code due to external api changes | 由于外部 API 更改而更新代码',
    name: 'alien',
    semver: 'patch',
  },
  {
    emoji: '🚚',
    entity: '&#1f69a;',
    code: ':truck:',
    description:
      'chore: move or rename resources (eg: files, paths, routes) | 移动或重命名文件',
    name: 'truck',
    semver: null,
  },
  {
    emoji: '🗃️',
    entity: '&#128451;',
    code: ':card_file_box:',
    description:
      'chore: perform database related changes | 执行与数据库相关的更改',
    name: 'card-file-box',
    semver: 'patch',
  },
  {
    emoji: '🤡',
    entity: '&#129313;',
    code: ':clown_face:',
    description: 'chore: mock things | mock 数据',
    name: 'clown-face',
    semver: null,
  },
  {
    emoji: '🙈',
    entity: '&#8bdfe7;',
    code: ':see_no_evil:',
    description:
      'chore: add or update a gitignore file | 添加或更新 .gitignore 文件',
    name: 'see-no-evil',
    semver: null,
  },
  {
    emoji: '🛂',
    entity: '&#x1f6c2;',
    code: ':passport_control:',
    description:
      'chore: work on code related to authorization, roles and permissions | 权限处理',
    name: 'passport-control',
    semver: 'patch',
  },
  {
    emoji: '🔥',
    entity: '&#x1f525;',
    code: ':fire:',
    description: 'chore(clean): remove code or files | 移除代码或文件',
    name: 'fire',
    semver: null,
  },
  {
    emoji: '⚰️',
    entity: '&#x26b0;',
    code: ':coffin:',
    description: 'chore(clean): remove dead code | 删除无效代码',
    name: 'coffin',
    semver: null,
  },
  {
    emoji: '🔊',
    entity: '&#128266;',
    code: ':loud_sound:',
    description: 'chore(logs): add or update logs | 添加日志',
    name: 'loud-sound',
    semver: null,
  },
  {
    emoji: '🔇',
    entity: '&#128263;',
    code: ':mute:',
    description: 'chore(logs): remove logs | 删除日志',
    name: 'mute',
    semver: null,
  },
];
